# Linear Algebra

**Overview**
This exercise introduces fundamental linear algebra operations in Numpy and how to use them to solve linear systems of equations. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#diff">Task 1: Elementwise difference</a>
            </li>
            <li>
            <a href="#mul_prop">Task 2: Multiplication properties</a>
            </li>
            <li>
            <a href="#elem_mul">Task 3: Elementwise multiplication - Hadamard pr…</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5],
    [3/2, 0.5],
    [0.25, 1]
])

## Matrix Operations

---
**Task 1 (easy): Elementwise difference👩‍💻**
1. Calculate $A-B$ in the code cell below.


---

In [4]:
# Write your solution here
A-B

array([[ 17.        , -14.5       ,  14.33333333, -12.75      ],
       [ 12.5       , -10.66666667,  10.25      ,  -8.8       ],
       [  8.33333333,  -6.75      ,   6.2       ,  -4.83333333],
       [  4.25      ,  -2.8       ,   2.16666667,  -0.85714286]])


---
**Task 2 (easy): Multiplication properties👩‍💻📽️**
1. Calculate $AC$ and $CA$ in the code cell below. (You may use either [`np.dot`
](https://numpy.org/doc/stable/reference/generated/numpy.dot.html<elem-3>.dot)
 or the `@`
 operator).

2. Explain why the results are different.

3. Calculate $DE$ and $ED$ in the code cell below.

4. Explain what happens and why.



---

In [ ]:
# Write your solution here
print("AC: \n", np.dot(A,C))
print("CA: \n", C@A)
"""
Since the dot-product is calculated by the inner-products of the left operands rows and the right operands columns, the values are different depending on which vector is which operand
(they are non-commutative)
"""

print("DE: \n", np.dot(D,E))
print("ED: \n", E@D)

"""
This does not work because D is a 3x3 matrix and E is a 3x2 matrix, and the left operand must have the same number of columns as the right has rows
This means that DE works since D has 3 columns and E has 3 rows, but ED does not work since E has 2 columns and D has 3 rows
"""

AC: 
 [[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
CA: 
 [[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]
DE: 
 [[8.625  3.5   ]
 [2.3125 1.625 ]
 [1.5    2.125 ]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


---
**Task 3 (easy): Elementwise multiplication - Hadamard product👩‍💻**
1. Calculate the elementwise multiplication of $A$ and $C$ using the `*`
 operator.
2. Explain the difference between the `*`
 and `@`
 operators and identify which one is matrix multiplication.


---

In [ ]:
# Write your solution here
print("A*C:\n", A*C)
print("A@C:\n", A@C)

"""
'*' multiplies each element with its respective counter-elements where '@' calculates the inner products between the vectors in the matrices. '@' is considered matrix multiplication
"""


A*C:
 [[1.         0.25       0.11111111 0.0625    ]
 [0.25       0.11111111 0.0625     0.04      ]
 [0.11111111 0.05       0.02857143 0.01851852]
 [0.0625     0.02857143 0.02083333 0.01587302]]
A@C:
 [[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]


---
