# Linear Algebra

**Overview**
This exercise is a continuation of week 3 exercise Basic Linear Algebra in Python
. It introduces how to solve linear systems of equations using linear algebra. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#inverses">Task 1: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 2: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 3: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 4: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 5: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 6: Implementing matrix multiplication</a>
            </li>
            <li>
            <a href="#extra">Task 7: Extra exercises</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)


---
**Task 1 (easy): Inverses👩‍💻**
1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. 


**Hint**
The question relates to the limitations of floating point numbers.


---

In [5]:
# Write your solution here
AI = np.linalg.inv(A)

AAI = A@AI

CI = np.linalg.inv(C)

CCI = C@CI

print("AI:",AI,"CI:",CI, sep="\n")

print()

print("AAI:", AAI, "CCI:", CCI, sep="\n")

AI:
[[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
CI:
[[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]

AAI:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.55431223e-15  1.00000000e+00 -2.38919995e-14 -5.98632255e-14]
 [ 1.11022302e-16 -3.44909286e-14  1.00000000e+00 -8.27486228e-14]
 [-3.45755171e-15  1.10387889e-14 -4.78981933e-14  1.00000000e+00]]
CCI:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-6.09734485e-14  1.00000000e+00  3.35864669e-13 -1.96731520e-14]
 [-4.02147451e-15 -8.61903141e-14  1.00000000e+00 -1.43342128e-14]
 [-4.02147451e-15  2.74965236e-14 -1.86591483e-13  1.00000000e+00]]


# 1. Results differ?
Yes slightly we expected all 0 cells to be zero but they are in fact just very close to zero aka e-15 but this is in fact a trick and is thus zero in reality frfr floats being floats

## Properties

---
**Task 2 (easy): Inverse properties👩‍💻**
Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$


---

In [ ]:
# Write your solution here

inv = np.linalg.inv

inv_sep = inv(D)@inv(E)
inv_together = inv(E@D)

print("sep:",inv_sep,"together:",inv_together, sep="\n")

inv_wrong = inv(D@E)

print("sep:",inv_sep,"wrong:",inv_wrong, sep="\n")

# YOU DAMN RIGHT ITS NOT THE SAME


sep:
[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
together:
[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
sep:
[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
wrong:
[[ 0.21096296 -0.256      -0.1517037 ]
 [-0.15365079  0.20571429  0.56634921]
 [ 0.05367196 -0.28342857  0.12833862]]



---
**Task 3 (easy): The determinant👩‍💻**
1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Determine which of the matrices $A,B,C$ have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-7>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).


---

In [21]:
# Write your solution here

lg = np.linalg

d_A = lg.det(A)
d_B= lg.det(B)
d_C= lg.det(C)

print(d_A, d_B, d_C, sep="\n")


print("inv A:\n",inv(A))
print("inv B:\n",inv(B))
print("inv C:\n",inv(C))

1.6534391534392702e-07
2.7733391199176e-32
1.0498026371041163e-07
inv A:
 [[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
inv B:
 [[-3.00239975e+16  4.80383960e+16 -6.00479950e+15 -1.20095990e+16]
 [-4.80383960e+16  7.20575940e+16 -0.00000000e+00 -2.40191980e+16]
 [-6.00479950e+15  0.00000000e+00  1.80143985e+16 -1.20095990e+16]
 [ 1.20095990e+16 -2.40191980e+16  1.20095990e+16 -0.00000000e+00]]
inv C:
 [[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]


# 2. Which have an inverse?
Maybe B is not but the rest are? idk bro

# 3. 

# 2. 


---
**Task 4 (easy): Transpose👩‍💻**
1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.


**Hint**
The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.


---

In [0]:
# Write your solution here

## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ the vector of unknowns, and $b$ is the vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$

---
**Task 5 (medium): Solving linear equation systems👩‍💻**
For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse. Your answers have to be submitted in [Grasple](https://app.grasple.com/#/courses/10532/ci/733997/diagnoses/12886)
:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$

---

In [35]:
# Write your solutions here
def create_design_matrix(inputs):
    return np.array([[c[0], 1] for c in inputs])

inputs1 = np.array([[2,3],[1,1]])
outputs1 = np.array([-1, 0])

weights1 = inv(inputs1)@outputs1

print(weights1)

inputs2 = np.array([[1,0],[0,1]])
outputs2 = np.array([5,7])

weights2 = inv(inputs2)@outputs2

print(weights2)

inputs3 = np.array([[0,1],[-2,-3]])
ouputs3 = np.array([-1,2])

weights3 = inv(inputs3)@ouputs3

print(weights3)

inputs4 = np.array([[1,-3,3],[1,-5,3],[4,-6,6]])
ouputs4 = np.array([0.5,0.5,1])

weights4 = inv(inputs4)@ouputs4

print(weights4)

inputs5 = np.array([[2,3,4],[1,1,4],[2,5,4]])
outputs5 = np.array([2,-2,3])

weights5 = inv(inputs5)@outputs5

print(weights5)

inputs6 = np.array([[1,1,1],[2,2,2],[3,3,3]])
outputs6 = np.array([2,-2,3])

weight6 = inv(inputs6)@outputs6

# No solution 
print(weight6)

[ 1. -1.]
[5. 7.]
[ 0.5 -1. ]
[-5.55111512e-17  1.58603289e-17  1.66666667e-01]
[ 3.     0.5   -1.375]
[-1.80143985e+16 -3.60287970e+16  5.40431955e+16]


## Matrix multiplication (optional)
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is an $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.

---
**Task 6 (medium): Implementing matrix multiplication👩‍💻**
Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.

**Hint**
It might be helpful to calculate the correct result by hand first, to make debugging easier.


---

In [0]:
def matmul(a, b):
    # Implement this function
    ...
    

ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

mb = [
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
]

matmul(ma, mb)


---
**Task 7 (easy): Extra exercises💡**
Additional exercises are available on Grasple. Complete these if you need more practice with fundamental linear algebra operations and properties:
1. [Matrix Operations](https://app.grasple.com/#/courses/10532/ci/694300/subjects/3936)

2. [Addition, Scalar Multiplication and Transposition](https://app.grasple.com/#/courses/10532/ci/694301/subjects/3935)

3. [Inverse Matrices](https://app.grasple.com/#/courses/10532/ci/735682/subjects/3939)



---